<link rel="stylesheet" href="/assets/client/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/client/css/owl.carousel.min.css">
<link rel="stylesheet" href="/assets/client/css/ticker-style.css">
<link rel="stylesheet" href="/assets/client/css/flaticon.css">
<link rel="stylesheet" href="/assets/client/css/slicknav.css">
<link rel="stylesheet" href="/assets/client/css/animate.min.css">
<link rel="stylesheet" href="/assets/client/css/magnific-popup.css">
<link rel="stylesheet" href="/assets/client/css/fontawesome-all.min.css">
<link rel="stylesheet" href="/assets/client/css/themify-icons.css">
<link rel="stylesheet" href="/assets/client/css/slick.css">
<link rel="stylesheet" href="/assets/client/css/nice-select.css">
<link rel="stylesheet" href="/assets/client/css/style.css">