<link rel="stylesheet" href="/client/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/client/assets/css/owl.carousel.min.css">
<link rel="stylesheet" href="/client/assets/css/ticker-style.css">
<link rel="stylesheet" href="/client/assets/css/flaticon.css">
<link rel="stylesheet" href="/client/assets/css/slicknav.css">
<link rel="stylesheet" href="/client/assets/css/animate.min.css">
<link rel="stylesheet" href="/client/assets/css/magnific-popup.css">
<link rel="stylesheet" href="/client/assets/css/fontawesome-all.min.css">
<link rel="stylesheet" href="/client/assets/css/themify-icons.css">
<link rel="stylesheet" href="/client/assets/css/slick.css">
<link rel="stylesheet" href="/client/assets/css/nice-select.css">
<link rel="stylesheet" href="/client/assets/css/style.css">